version: "3"
services:
  django:
    environment:
      - "STATIC_ROOT=/var/lib/static"
    volumes:
      - "./server:/usr/src/app"
      - "django_static:/var/lib/static"
      - "./server/upload_images:/usr/src/app/upload_images"
    restart: always
  postgres:
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.prod.conf:/etc/nginx/templates/default.conf.template"
      - "circle_site_dist:/usr/src/app/circle_site"
      - "django_static:/usr/src/app/django_static"
      - "./server/upload_images:/usr/src/app/upload_images"
    restart: always
  circle_site:
    volumes:
      - "circle_site_dist:/usr/src/app/dist"

volumes:
  database:
    driver: local
  django_static:
    driver: local
  circle_site_dist:
    driver: local