version: "3"
services:
  django:
    environment:
      - "STATIC_ROOT=/var/lib/static"
    volumes:
      - "./server:/usr/src/app"
      - "django_static:/var/lib/static"
      - "./server/upload_images:/usr/src/app/upload_images"
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.prod.conf:/etc/nginx/nginx.conf"
      - "django_static:/usr/src/app/django_static"
      - "./server/upload_images:/usr/src/app/upload_images"
    ports:
      - "8008:80"

volumes:
  database:
    driver: local
  django_static:
    driver: local
