version: "3"
services:
  django:
    build: server
    links:
      - "postgres"
    env_file:
      - ".env"
    volumes:
      - "./server:/usr/src/app"
      - "./server/upload_images:/usr/src/app/upload_images"
  postgres:
    image: postgres:12-alpine
    env_file:
      - ".env"
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - "django"

volumes:
  database:
    driver: local
