# Generated by Django 3.1.1 on 2021-04-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('family_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='姓')),
                ('given_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='名')),
                ('family_name_ruby', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='姓フリガナ')),
                ('given_name_ruby', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='名フリガナ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('courses', models.CharField(choices=[('none', 'なし'), ('engineering', 'エンジニアリングコース'), ('design', 'デザインコース'), ('business', 'ビジネスコース'), ('civil-system', 'シビルシステムコース')], default='none', max_length=12, verbose_name='コース')),
                ('interested_in', models.JSONField(verbose_name='興味')),
                ('questionnaire', models.JSONField(verbose_name='アンケート')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
