# Generated by Django 3.1.1 on 2021-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='courses',
            new_name='course',
        ),
    ]
