# Generated by Django 3.1.1 on 2021-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ob_og',
            field=models.BooleanField(default=False, verbose_name='OB・OG'),
        ),
    ]
