# Generated by Django 3.1.1 on 2020-11-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20201129_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
    ]
