# Generated by Django 3.1.1 on 2020-11-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_remove_article_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sns_publish_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SNS告知文'),
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='sns_publish_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SNS告知文'),
        ),
    ]
