# Generated by Django 3.1.1 on 2020-12-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0010_prearticle_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='times.lecture', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prearticle', to='times.lecture', verbose_name='授業'),
        ),
    ]
