# Generated by Django 3.1.1 on 2020-12-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0011_auto_20201201_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_user',
            new_name='last_staff',
        ),
        migrations.RenameField(
            model_name='prearticle',
            old_name='user',
            new_name='last_staff',
        ),
    ]
