# Generated by Django 3.1.1 on 2020-12-02 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0012_auto_20201201_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='eyecatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_article', to='times.image', verbose_name='アイキャッチ画像'),
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='eyecatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_prearticle', to='times.image', verbose_name='アイキャッチ画像'),
        ),
    ]
