# Generated by Django 3.1.1 on 2020-12-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0013_auto_20201202_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearticle',
            name='revise_count',
            field=models.IntegerField(default=0, verbose_name='校閲完了数'),
        ),
        migrations.CreateModel(
            name='PreArticleWriterRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_writer_checked', models.BooleanField(default=False, verbose_name='筆者確認済み')),
                ('prearticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_relations', to='times.prearticle')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote_prearticle_relations', to='times.staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='prearticle',
            name='article_writers',
        ),
        migrations.AddField(
            model_name='prearticle',
            name='article_writers',
            field=models.ManyToManyField(blank=True, related_name='wrote_prearticle', through='times.PreArticleWriterRelation', to='times.Staff', verbose_name='執筆者'),
        ),
    ]
