# Generated by Django 3.1.1 on 2020-12-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0018_auto_20201207_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prearticle',
            old_name='is_final_check',
            new_name='is_final',
        ),
    ]
