# Generated by Django 3.1.1 on 2020-11-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20201129_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prearticle',
            old_name='is_editor',
            new_name='is_revision',
        ),
    ]
