# Generated by Django 3.1.1 on 2020-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0006_auto_20201130_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_publishable',
            field=models.BooleanField(default=False, verbose_name='公開準備済'),
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='is_revision',
            field=models.BooleanField(default=False, verbose_name='校閲か'),
        ),
    ]
