# Generated by Django 3.1.1 on 2020-11-30 13:51

from django.db import migrations, models
import uuid

def gen_uuid_article(apps, schema_editor):
    MyModel = apps.get_model('times', 'Article')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

def gen_uuid_prearticle(apps, schema_editor):
    MyModel = apps.get_model('times', 'PreArticle')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_auto_20201130_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='prearticle',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True, verbose_name='UUID'),
        ),
        migrations.RunPython(gen_uuid_article, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_prearticle, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),  # ユニーク制約を追加
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),  # ユニーク制約を追加
            preserve_default=False,
        ),
    ]
