# Generated by Django 3.1.1 on 2020-11-30 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0008_auto_20201130_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearticle',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='下書きか'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='prearticle',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
