# Generated by Django 3.1.1 on 2020-12-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0009_auto_20201130_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearticle',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='INIAD関係者以外の閲覧を許可する'),
        ),
    ]
