# Generated by Django 3.1.1 on 2020-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0014_auto_20201202_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Page URL'),
        ),
        migrations.AddField(
            model_name='prearticle',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Page URL'),
        ),
    ]
