# Generated by Django 3.1.1 on 2020-12-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0016_auto_20201206_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prearticlewriterrelation',
            name='is_writer_checked',
        ),
        migrations.AddField(
            model_name='prearticle',
            name='is_revision_checked',
            field=models.BooleanField(default=False, verbose_name='校閲チェック完了'),
        ),
        migrations.AddField(
            model_name='prearticle',
            name='is_revision_rejected',
            field=models.BooleanField(default=False, verbose_name='校閲リジェクト'),
        ),
        migrations.AddField(
            model_name='prearticlewriterrelation',
            name='writer_check',
            field=models.IntegerField(choices=[(0, '未確認'), (1, '承認'), (-1, '拒否')], default=0, verbose_name='筆者確認済み'),
        ),
    ]
