# Generated by Django 3.1.1 on 2020-12-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0019_auto_20201207_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prearticle',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='公開直前版か'),
        ),
    ]
