# Generated by Django 3.1.1 on 2020-12-07 02:31

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0020_auto_20201207_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(upload_to='upload_images'),
        ),
    ]
