# Generated by Django 3.1.1 on 2021-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0021_auto_20201207_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='screen_name',
            field=models.SlugField(blank=True, default='', max_length=20, null=True, verbose_name='スクリーンネーム'),
        ),
    ]
