# Generated by Django 3.1.1 on 2021-02-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0022_auto_20210217_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='screen_name',
            new_name='slug',
        ),
    ]
